[project]
name = "source-code-classification"
authors = [{name = "cristiano2003", email = "nguyentrungtruc2003@gmail.com"}]
version = "1.0.0"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "lightning",
    "torchsummary",
    "transformers",
    "datasets",
    "rouge",
    "torchmetrics"
]

[project.optional-dependencies]
dev = [
    "pytest"
]